services:
  dialogue:
    command: --debug --host mqtt --port 12183 --site-id default --session-timeout
      30 --sound wake /usr/lib/rhasspy/etc/wav/beep_hi.wav --sound recorded /usr/lib/rhasspy/etc/wav/beep_lo.wav
      --sound error /usr/lib/rhasspy/etc/wav/beep_error.wav --volume 1 --min-asr-confidence
      0 --say-chars-per-second 33 --sound-suffix .wav --sound-suffix .mp3 --sound-suffix
      .ogg --sound-suffix .flac
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-dialogue-hermes
    tty: true
  intent_recognition:
    command: --intent-graph /profiles/es/intent_graph.pickle.gz --debug --host mqtt
      --port 12183 --site-id default --replace-numbers --language es_ES --casing lower
      --converters-dir /profiles/es/converters --failure-token <unk>
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-nlu-hermes
    tty: true
    volumes:
    - /profiles:/profiles
  microphone:
    command: --sample-rate 16000 --sample-width 2 --channels 1 --debug --host mqtt
      --port 12183 --site-id default --udp-audio-host 127.0.0.1 --frames-per-buffer
      1024
    depends_on:
    - mqtt
    devices:
    - /dev/snd
    image: rhasspy/rhasspy-microphone-pyaudio-hermes
    tty: true
  mqtt:
    command: -p 12183
    entrypoint: mosquitto
    image: eclipse-mosquitto
    ports:
    - 12183:12183
    tty: true
  speakers:
    command: --play-command 'aplay -q -t wav -D hw:CARD=Device_1,DEV=0' --list-command
      'aplay -L' --volume 1 --debug --host mqtt --port 12183 --site-id default
    depends_on:
    - mqtt
    devices:
    - /dev/snd
    image: rhasspy/rhasspy-speakers-cli-hermes
    tty: true
  speech_to_text:
    command: --acoustic-model /profiles/es/acoustic_model --dictionary /profiles/es/dictionary.txt
      --language-model /profiles/es/language_model.txt --debug --host mqtt --port
      12183 --site-id default --intent-graph /profiles/es/intent_graph.pickle.gz --base-dictionary
      /profiles/es/base_dictionary.txt --base-dictionary /profiles/es/custom_words.txt
      --dictionary-casing lower --g2p-model /profiles/es/g2p.fst --unknown-words /profiles/es/unknown_words.txt
      --base-language-model-fst /profiles/es/base_language_model.fst --base-language-model-weight
      0 --mixed-language-model-fst /profiles/es/mixed.fst --voice-skip-seconds 0 --voice-min-seconds
      1 --voice-max-seconds 20 --voice-speech-seconds 0.3 --voice-silence-seconds
      0.5 --voice-before-seconds 0.5 --voice-sensitivity 1 --voice-silence-method
      vad_only
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-asr-pocketsphinx-hermes
    tty: true
    volumes:
    - /profiles:/profiles
  text_to_speech:
    command: --tts-command 'espeak --stdout -v {lang}' --voices-command 'espeak --voices
      | tail -n +2 | awk '"'"'{ print $2,$4 }'"'"'' --language es --volume 1 --debug
      --host mqtt --port 12183 --site-id default
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-tts-cli-hermes
    tty: true
  wake:
    command: --keyword porcupine.ppn --sensitivity 0.5 --keyword-dir /profiles/es/porcupine
      --debug --host mqtt --port 12183 --site-id default
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-wake-porcupine-hermes
    tty: true
    volumes:
    - /profiles:/profiles
version: '2'
